controle_atividades/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth import login

from .views import (home, courses,
                    course, activity, activities,
                    register_student, questions)

urlpatterns = [
    path('', home, name='core_home'),
    path('cursos', courses, name='courses'),
    path('cursos/<int:courseId>', course, name='course'),
    path('atividades', activities, name='activities'),
    path('atividades/<int:activityId>', activity, name='activity'),
    path('cadastro_aluno', register_student, name='register_student'),
    path('questoes', questions, name='questions')
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils.models import SoftDeletableModel, TimeStampedModel
import uuid


class Students(SoftDeletableModel, TimeStampedModel):
    """Model definition for Students."""

    # TODO: Define fields here
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subscription = models.CharField(max_length=8, editable=False)
    name = models.CharField('Nome', max_length=100)

    class Meta:
        """Meta definition for Students."""

        verbose_name = 'Estudante'
        verbose_name_plural = 'Estudantes'

    def __str__(self):
        """Unicode representation of Students."""
        return self.name
    # Fiz um override o save default
    def save(self):
        # toda vez que o save é chamado em alguma parte do codigo, indiretamente ele entra nesse save aqui
        # dai o que fiz foi adicionar esse uuid, tranformando ele em string e pegando os 6 primeiros caracteres
        # logo em seguida eu dei um "super" que vai ser responsavel por da seguimento a função save e vai salvar
        # os demais campos normalmente
        self.subscription = str(uuid.uuid4().time_low)[:6]
        super(Students, self).save()


class Course(SoftDeletableModel, TimeStampedModel):
    """Model definition for Curso."""

    PERIOD_TYPE = [
        ('morning', 'Manhã'),
        ('afternoon', 'Tarde'),
        ('night', 'Noite'),
    ]

    # TODO: Define fields here
    students = models.ManyToManyField(
        Students, verbose_name='Estudantes', blank=True)
    name = models.CharField('Nome', max_length=100)
    tag = models.CharField('Abreviação', max_length=10, null=True, blank=True)
    period = models.CharField('Período', max_length=50, choices=PERIOD_TYPE)

    class Meta:
        """Meta definition for Curso."""

        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

    def __str__(self):
        """Unicode representation of Curso."""
        return self.name


class Activity(SoftDeletableModel, TimeStampedModel):
    """Model definition for Activity."""

    # TODO: Define fields here
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=100, null=True)
    time_start = models.DateTimeField(
        'Hora de início', auto_now=False, auto_now_add=False)

    class Meta:
        """Meta definition for Activity."""

        verbose_name = 'Atividade'
        verbose_name_plural = 'Atividades'

    def __str__(self):
        """Unicode representation of Activity."""
        return 'Curso: {} - Atividade: {}'.format(self.course.name, self.name)


class FinalGrade(SoftDeletableModel, TimeStampedModel):
    """Model definition for FinalGrade."""

    # TODO: Define fields here
    student = models.ForeignKey(
        Students, verbose_name='Estudante', on_delete=models.CASCADE)
    activity = models.ForeignKey(
        Activity, verbose_name='Atividade', on_delete=models.CASCADE)
    grade = models.DecimalField('Nota', max_digits=5, decimal_places=2)

    class Meta:
        """Meta definition for FinalGrade."""

        verbose_name = 'Nota Final'
        verbose_name_plural = 'Notas Finais'

    def __str__(self):
        """Unicode representation of FinalGrade."""
        return self.student.name


class Questions(SoftDeletableModel, TimeStampedModel):
    """Model definition for Questions."""

    ALTERNATIVES = [
        ('a', 'A)'),
        ('b', 'B)'),
        ('c', 'C)'),
        ('d', 'D)'),
    ]

    # TODO: Define fields here
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    question = models.TextField()
    value_question = models.DecimalField(
        'Valor da pergunta', max_digits=5, decimal_places=2)
    response = models.CharField(
        'Resposta', max_length=100, blank=True, null=True)
    correct_alternative = models.CharField(
        'Alternativa Correta', max_length=50, choices=ALTERNATIVES)
    wrong_alternative = models.ManyToManyField(
        'WrongAlternative', verbose_name='Respostas incorretas')

    class Meta:
        """Meta definition for Questions."""

        verbose_name = 'Questão'
        verbose_name_plural = 'Questões'

    def __str__(self):
        """Unicode representation of Questions."""
        return self.question


class WrongAlternative(SoftDeletableModel, TimeStampedModel):

    ALTERNATIVES = [
        ('a', 'A)'),
        ('b', 'B)'),
        ('c', 'C)'),
        ('d', 'D)'),
    ]

    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    response = models.CharField('Resposta', max_length=100)
    alternative = models.CharField(
        'Alternativa incorreta', max_length=50, choices=ALTERNATIVES)

    class Meta:
        """Meta definition for Response."""

        verbose_name = 'Alternativa Incorreta'
        verbose_name_plural = 'Alternativas Incorretas'

    def __str__(self):
        """Unicode representation of Response."""
        return '{} - {}) {}'.format(self.activity.name, self.alternative, self.response)

core/forms.py
from django import forms
from .models import Students, Course, Activity


class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = '__all__'


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect
from .models import Students, Course, Activity, Questions, WrongAlternative
from .forms import StudentsForm, CourseForm, ActivityForm
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required


@login_required()
def home(request):
    template_name = 'base.html'
    return render(request, template_name)


@login_required()
def register_student(request):
    template_name = 'register_student.html'
    if request.method == 'POST':
        user = request.POST['user']
        email = request.POST['email']
        senha = request.POST['senha']
        name = request.POST['name']
        newUser = User.objects.create_user(
            username=user, email=email, password=senha)
        newUser.save()
        student = Students.objects.create(user=newUser, name=name)
        my_group = Group.objects.get(name='aluno')
        my_group.user_set.add(newUser)
        msg = 'true'

        return render(request, template_name, locals())
    return render(request, template_name, locals())


@login_required()
def courses(request):
    """This view is reponsible for creating and listing"""
    template_name = 'course.html'
    form = CourseForm(request.POST or None)
    courses = Course.objects.all()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('courses')
    return render(request, template_name, locals())


@login_required()
def course(request, courseId):
    """This view is reponsible for updating and deleting"""
    template_name = 'course.html'
    course = Course.objects.get(id=courseId)
    courses = Course.objects.all()
    form = CourseForm(request.POST or None, instance=course)

    if request.method == 'POST':
        if 'SAVE' in request.POST:
            if form.is_valid():
                form.save()
        if 'DELETE' in request.POST:
            course.delete()
        return redirect('courses')
    return render(request, template_name, locals())


@login_required()
def activities(request):
    """This view is reponsible for creating and listing"""
    template_name = 'activity.html'
    form = ActivityForm(request.POST or None)
    activities = Activity.objects.all()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('activities')
    return render(request, template_name, locals())


@login_required()
def activity(request, activityId):
    """This view is reponsible for updating and deleting"""
    template_name = 'activity.html'
    activity = Activity.objects.get(id=activityId)
    activities = Activity.objects.all()
    form = ActivityForm(request.POST or None, instance=activity)

    if request.method == 'POST':
        if 'SAVE' in request.POST:
            if form.is_valid():
                form.save()
        if 'DELETE' in request.POST:
            activity.delete()
        return redirect('activities')
    return render(request, template_name, locals())


def questions(request):
    """This view is reponsible for creating and listing"""
    activities = Activity.objects.all()
    template_name = 'question.html'

    # faço uma lista simples com todas as letras possiveis, ela basicamente será usada para marcar as respostas erradas
    alternatives = ['a', 'b', 'c', 'd']

    if request.method == 'POST':
        if 'SAVE' in request.POST:
            activity_id = request.POST['activity']
            question = request.POST['question']
            value_question = request.POST['value_question']
            response = request.POST['response']
            correct_alternative = request.POST['correct_alternative']

            # desse jeito eu consigo pegar uma lista de objetos que vem no request
            # a sacada por tras do envio de lista pelo request, está no macete de vc colocar
            # os campos que vc quer como lista tem que ter todos o mesmo "name" no html
            # observe que existe 3 campos para resposta errada e os 3 ta com mesmo "name" e "id"
            # com isso o retorno no request vem em uma lista
            wrong_responses = request.POST.getlist('wrong_response')

            # Removo a letra que foi escolhida para a resposta correta
            alternatives.remove(correct_alternative)

            # quando eu seleciono uma atividade é enviado o id de tal atividade
            activity = Activity.objects.get(id=activity_id)

            # Crio um instancia do questions e monto todo o objeto com o que vem do request
            quest = Questions()
            quest.activity = activity
            quest.question = question
            quest.value_question = value_question
            quest.response = response
            quest.correct_alternative = correct_alternative
            quest.save()

            # esse enumerate serve pra retornar o valor da lista + um index, ele é bom pra situações
            # que vc vai precisar de um "contador"
            for index, wrong_response in enumerate(wrong_responses):
                wrong = WrongAlternative()
                wrong.response = wrong_response
                wrong.alternative = alternatives[index]
                wrong.activity = activity
                wrong.save()
                # essa é a forma de vc inserir valor em um campo manytomany
                quest.wrong_alternative.add(wrong)

    return render(request, template_name, locals())

core/templates/activity.html
{% extends "base_add_list.html" %}
{% load bootstrap %}

{% comment %} INSERT {% endcomment %}
{% block insert_title %}Cadastrar Atividade{% endblock insert_title %}

{% block menu %}
{% include 'core/menu.html' %}
{% endblock %}

{% block insert_data %}
<form action="
    {% if activityId %}
        {% url 'activity' activityId %}
    {% else %}
        {% url 'activities' %}
    {% endif %}" method=" POST">
    {% csrf_token %}
    {{ form.course|bootstrap }}
    {{ form.name|bootstrap }}
    {{ form.time_start|bootstrap }}
    <button type="submit" class="btn btn-primary"
        name='SAVE'>{% if activityId %}Atualizar{% else %}Salvar{% endif %}</button>
    {% if activityId %}<button type="submit" class="btn btn-danger" name='DELETE'>Deletar</button>{% endif %}
</form>
{% endblock insert_data %}

{% comment %} LIST {% endcomment %}
{% block list_title %}Lista de Atividades{% endblock list_title %}
{% block list_columns %}
<tr>
    <th>Curso</th>
    <th>Nome</th>
    <th colspan='2'>Periodo</th>
</tr>
{% endblock list_columns %}
{% block list_data %}
{% for activity in activities %}
<tr>
    <td>{{ activity.course.name }}</td>
    <td>{{ activity.name }}</td>
    <td class='w-45'>{{ activity.time_start }}</td>
    <td class='text-right'>
        <a href="{% url 'activity' activity.id %}">
            <i class="fa fa-pencil fa-lg text-info"></i>
        </a>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan='2' class='text-center'>Ainda não existe atividades cadastradas</td>
</tr>
{% endfor %}
{% endblock list_data %}

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Control Activity{% endblock %}</title>

    <link
            rel="stylesheet"
            media="all"
            href="{% static 'font-awesome/css/font-awesome.css' %}"
            type="text/css"
            charset="utf-8"
    />
    <link
            rel="stylesheet"
            media="all"
            href="{% static 'bootstrap/dist/css/bootstrap.css' %}"
            type="text/css"
            charset="utf-8"
    />
</head>

<body>

    {% block menu %} {% endblock %}

<div class="row"></div>
<div class="container mt-5">
    {% block main %} {% endblock %}
</div>

<script src="{% static 'jquery/jquery.js'%}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.js'%}"></script>
<script src="{% static 'popper.js/dist/popper.js'%}"></script>
{% block script %} {% endblock %}
</body>
</html>

core/templates/base_add_list.html
{% extends "base.html" %}
{% block main %}

<div class="row">
    {% comment %} list items {% endcomment %}
    <div class="col-12 mb-5">
        <div class="card shadow-sm">
            <div class="card-body">
                <h5 class="card-title">
                    {% block insert_title %}
                    {% endblock insert_title %}
                </h5>
                {% block insert_data %}
                {% endblock insert_data %}
            </div>
        </div>
    </div>

    {% comment %} add item {% endcomment %}
    <div class="col-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <h5 class="card-title">
                    {% block list_title %}
                    {% endblock list_title %}
                </h5>
                <p>
                    {% block list_help %}
                    {% endblock list_help %}
                </p>
                <table class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        {% block list_columns %}
                        {% endblock list_columns %}
                    </thead>
                    <tbody>
                        {% block list_data %}
                        {% endblock list_data %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

core/templates/course.html
{% extends "base_add_list.html" %}
{% load bootstrap %}

{% comment %} INSERT {% endcomment %}
{% block insert_title %}Cadastrar curso{% endblock insert_title %}

{% block menu %}
{% include 'core/menu.html' %}
{% endblock %}

{% block insert_data %}
<form action="{% if courseId %}
        {% url 'course' course.id %}
    {% else %}
        {% url 'courses' %}
    {% endif %}" method="POST">
    {% csrf_token %}
    {{ form.name|bootstrap }}
    {{ form.period|bootstrap }}
    <button type="submit" class="btn btn-primary"
        name='SAVE'>{% if courseId %}Atualizar{% else %}Salvar{% endif %}</button>
    {% if courseId %}<button type="submit" class="btn btn-danger" name='DELETE'>Deletar</button>{% endif %}
</form>
{% endblock insert_data %}

{% comment %} LIST {% endcomment %}
{% block list_title %}Lista de Cursos{% endblock list_title %}
{% block list_columns %}
<tr>
    <th>Curso</th>
    <th colspan='2'>Periodo</th>
</tr>
{% endblock list_columns %}
{% block list_data %}
{% for course in courses %}
<tr>
    <td>{{ course.name }}</td>
    <td class='w-75'>{{ course.get_period_display }}</td>
    <td class='text-right'>
        <a href="{% url 'course' course.id %}" class='pr-2'>
            <i class="fa fa-pencil fa-lg text-info"></i>
        </a>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan='2' class='text-center'>Ainda não existe cursos cadastrados</td>
</tr>
{% endfor %}
{% endblock list_data %}

core/templates/question.html
{% extends "base_add_list.html" %}
{% load bootstrap %}

{% block insert_title %}Cadastrar questões{% endblock insert_title %}

{% block menu %}
{% include 'core/menu.html' %}
{% endblock %}

{% block insert_data %}
<form action="{% url 'questions' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="activity">Selecione a materia</label>
        <select class="form-control" name="activity" id="activity">
            <option value=""></option>
            {% for activity in activities %}
            <option value="{{ activity.id }}">{{activity.course.tag}} - {{ activity.name }} </option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="question">Questão</label>
        <textarea class="form-control" name="question"></textarea>
    </div>
    <div class="form-row">
        <div class="col-8">
            <label for="response">Resposta Correta</label>
            <input type="text" class="form-control" aria-label="Text input with radio button" name="response">
        </div>
        <div class="col-2">
            <label for="response">Letra Correta</label>
            <select name="correct_alternative" id="correct_alternative" class="form-control">
                <option value=""></option>
                <option value="a">A</option>
                <option value="b">B</option>
                <option value="c">C</option>
                <option value="d">D</option>
            </select>
        </div>
        <div class="col-2">
            <label for="value_question">Valor da resposta</label>
            <input type="number" name="value_question" id="value_question" class="form-control">
        </div>
    </div>
    <div class="form-row mt-3">
        <div class="col-12">
            <label for="response">Respostas incorretas</label>
            <div class="form-group">
                <input type="text" class="form-control" aria-label="Text input with radio button" name="wrong_response">
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <input type="text" class="form-control" aria-label="Text input with radio button" name="wrong_response">
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <input type="text" class="form-control" aria-label="Text input with radio button" name="wrong_response">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary" name='SAVE'>Salvar</button>
</form>
{% endblock insert_data %}

core/templates/register_student.html
{% extends "base.html" %}
{% block title %}Cadastro de estudante{% endblock %}

{% block menu %}
{% include 'core/menu.html' %}
{% endblock %}

{%block main %}

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="card w-100">
            <div class="card-body">
                {% if msg == 'true' %}
                <span style="color: green"> Cadastro efetuado com sucesso!</span>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Nome</label>
                        <input
                                type="name"
                                class="form-control"
                                id="name"
                                name="name"
                                placeholder="insira seu nome aqui"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="userName">Usuário</label>
                        <input
                                type="name"
                                class="form-control"
                                id="userName"
                                name="user"
                                placeholder="insira seu usuário"
                                required
                        />
                    </div>
                    <div class="form-group was-validated">
                        <label for="exampleFormControlInput1">Endereço de email</label>
                        <input
                                type="email"
                                class="form-control"
                                id="exampleFormControlInput1"
                                name="email"
                                placeholder="nome@exemplo.com"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Senha</label>
                        <input
                                type="password"
                                class="form-control"
                                id="exampleInputPassword1"
                                name="senha"
                                placeholder="Senha"
                                required
                        />
                    </div>
                    <button class="btn btn-primary">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

core/templates/student.html
{% extends "base_add_list.html" %}
{% load bootstrap %}

{% comment %} INSERT {% endcomment %}
{% block insert_title %}Cadastrar aluno{% endblock insert_title %}
{% block insert_data %}
<form action="
    {% if studentId %}
        {% url 'student' studentId %}
    {% else %}
        {% url 'students' %}
    {% endif %}" method="POST">
    {% csrf_token %}
    {{ form.user|bootstrap }}
    {{ form.subscription|bootstrap }}
    {{ form.name|bootstrap }}
    <button type="submit" class="btn btn-primary" name='SAVE'>{% if studentId %}Atualizar{% else %}Salvar{% endif %}</button>
    {% if studentId %}<button type="submit" class="btn btn-danger" name='DELETE'>Deletar</button>{% endif %}
</form>
{% endblock insert_data %}
{% comment %} END INSERT {% endcomment %}

{% comment %} LIST {% endcomment %}
{% block list_title %}Lista de alunos{% endblock list_title %}

{% block list_columns %}
<tr>
    <th>Matricula</th>
    <th colspan='2'>Nome</th>
</tr>
{% endblock list_columns %}

{% block list_data %}
{% for student in students %}
<tr>
    <td>{{ student.subscription }}</td>
    <td class='w-75'>{{ student.name }}</td>
    <td class='text-right'>
        <a href="{% url 'student' student.id %}" class='pr-2'>
            <i class="fa fa-pencil fa-lg text-info"></i>
        </a>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan='2' class='text-center'>Ainda não existe alunos cadastrados</td>
</tr>
{% endfor %}
{% endblock list_data %}
{% comment %} END LIST {% endcomment %}